"""rename department

Revision ID: 7fd29491edcf
Revises: a8dfc19d63ba
Create Date: 2024-10-01 13:36:13.943935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd29491edcf'
down_revision = 'a8dfc19d63ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
